### ISSUE TITLE
Results of training on NYU dataset？

### ISSUE THREAD

**Issue by luckyday2022** [ru1ven/KeypointFusion#1]

**Comment by ru1ven** [comment]
[train_NYU_without_real_root.log](https://github.com/ru1ven/KeypointFusion/files/14997412/train_NYU_without_real_root.log)
Here is the training log of Keypoint-Fusion on NYU. The backbone is ConvNeXt-tiny.

**Comment by luckyday2022** [comment]
Have you conducted experiments on the MSRA and ICVL dataset? Can you provide the dataloader of these two datasets?

**Comment by ru1ven** [comment]
Sorry, we only use these RGB-D datasets: DexYCB, HO-3D, STB, and NYU.
